YP_PATH='/Users/vhong/workspace/yourPeople3'
YP2_PATH='/Users/vhong/workspace/yourPeople3_2'

alias zendb7='/Users/vhong/workspace/zendb/zendb7'

get_all_yp_paths() {
    local yp_path=$@
    local additional_paths=$(PYTHONPATH=$yp_path python -c "from yourpeople.settings import ADDITIONAL_PATH_APPENDS; print ':'.join(ADDITIONAL_PATH_APPENDS)")
    echo $yp_path:$additional_paths
}

alias yp='cd $YP_PATH'
alias ype='nvm use v4.8.6 && export PYTHONPATH=$(get_all_yp_paths $YP_PATH) && export YP3=$YP_PATH && cd $YP_PATH'

alias yp2='cd $YP2_PATH'
alias ype2='nvm use v4.8.6 && export PYTHONPATH=$(get_all_yp_paths YP2_PATH) && export YP3=$YP2_PATH && cd $YP2_PATH'

alias pm='python manage.py '
alias pmt='python manage.py test --reusedb --settings=yourpeople.test_local_settings '

alias ypuwsgi='uwsgi $YP_PATH/yourpeople/uwsgi-dev.ini --home $(pyenv root)/versions/yp'
alias yp2uwsgi='uwsgi $YP2_PATH/yourpeople/uwsgi-dev.ini --home $(pyenv root)/versions/yp2a'

alias moto='moto_server swf'
alias smtp='sudo python -m smtpd -n -c DebuggingServer localhost:25'

alias pir='pip install -r requirements.txt'

# z-frontend development env setups
Z_FRONTEND_PATH='/Users/vhong/workspace/z-frontend'

alias zf="nvm use lts/dubnium && export PATH=$Z_FRONTEND_PATH/node_modules/.bin:$PATH && cd $Z_FRONTEND_PATH"

# Color output for ls.
alias ls='ls -G'

alias grep='grep --color'
alias ag='ag --color'

# Source common aliases
source $HOME/.dotfiles/bash/common/bash_aliases
