# Up directories.
alias u="cd .."
alias u2="cd ../.."
alias u3="cd ../../.."
alias u4="cd ../../../.."
alias u5="cd ../../../../.."

# Some ls aliases.
alias ll="ls -alF"
alias la="ls -A"
alias l="ls -CF"

# Some grep aliases.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Tell less to keep color from pipe.
alias less='less -R'

# Favorite editors
alias vi='nvim'
alias vim='nvim'
