# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Alias definitions.
if [ -f $HOME/.bash_aliases ]; then
    . $HOME/.bash_aliases
fi

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options.
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it.
shopt -s histappend

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=5000
HISTFILESIZE=10000

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# Set my favourite editor
export EDITOR="vim"

# Read man with vim
man() {
  /usr/bin/man $* | \
    col -b | \
    vim -R -c 'set ft=man nomod nolist' -
}

psgrep() {
  # Run `ps aux | grep [a]rg`
  local arg="$@"
  ps aux | grep "[${arg:0:1}]${arg:1}"
}

# Use bash-git-prompt
export GIT_PROMPT_ONLY_IN_REPO=1
export GIT_PROMPT_END="$ "
source ~/.dotfiles/bash/plugins/bash-git-prompt/gitprompt.sh
