# Color output for ls.
alias ls='ls --color=auto'

# Alias for open default program.
alias xo="xdg-open"

# CSE ssh login.
alias csessh="ssh -X tvho795@login.cse.unsw.edu.au"
# Sosub ssh login.
alias sossh="ssh vy@61.14.235.124"

# Convenient alias for sosub
alias ssd="cd ~/workspace/sosub"
alias sse="cd ~/workspace/sosub && pyenv activate sosubvenv"

# Source common aliases
source $HOME/.dotfiles/bash/common/bash_aliases
