# Dependencies:
# - Oh-my-zsh
#   + Description: Collection of useful plugins and themes for zsh.
#   + Installation: https://github.com/robbyrussell/oh-my-zsh#getting-started
# - PowerLine fonts
#   + Description: Many themes in oh-my-zsh relies on these fonts.
#   + Installation: https://github.com/powerline/fonts#installation
# - Antibody
#   + Description: plugin manager for zsh.
#   + Installation: https://getantibody.github.io/install/

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
# Set name of the theme to load
ZSH_THEME="af-magic"
# _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"
# Different timestamp format for `history` command
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    colored-man-pages
    colorize
    fzf
)

source $ZSH/oh-my-zsh.sh

# Statically load plugins from antibody
source ~/.zsh_plugins.sh
# Command to rebuild antibody plugins.
# Should be run everytime we add new plugin through antibody.
zsh_build_plugins() {
    antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh
}

# User configuration
# Add fzf to path
export PATH="$PATH:$HOME/.fzf/bin"

# pyenv-virtualenv
export PYENV_ROOT="$HOME/.pyenv"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Set my favourite editor
export EDITOR="vim"

# Source aliases
source $HOME/.zsh_aliases
